fix(add brand icon half tone): add half tone fill to One brand icon
Legal-and-General/canopy pull request #1393
Opened 2024-04-30 14:59 UTC by IdaHW

# Description

Add half tone fill to the One brand icon as part of Dotcom bug https://landg.atlassian.net/browse/LGCOM-10826

# Checklist:

- [x] The commit messages follow the [convention for this project](./blob/master/docs/CONTRIBUTING.md#conventional-commits)

2024-05-01 11:54 UTC, Xinchro submitted a review, later dismissed

2024-05-01 12:21 UTC, paul-request submitted a review, later dismissed

2024-05-03 11:17 UTC, pauleustice commented
@IdaHW I changed the base branch to `next`, but that unfortunately means your PR now brings in a commit by Jay from master. Have DMd you the cleanest way to update/force push your branch.

Do not merge this PR as it is

2024-05-03 11:17 UTC, pauleustice requested changes
Blocking merge until branch udpated

2024-05-08 07:59 UTC, closed without merging