fix(code-ql): update camel case pipe regex
Legal-and-General/canopy pull request #197
Opened 2021-02-03 17:34 UTC by elenagarrone

# Description

Apparently there was another instance of the insufficient regular expression.

# Checklist:

- [x] The commit messages follow the [convention for this project](./blob/master/docs/CONTRIBUTING.md#conventional-commits)
- [ ] I have provided an adequate amount of test coverage
- [ ] I have added the functionality to the [test app](./blob/master/docs/CONTRIBUTING.md#build-test-application)
- [ ] I have provided a story in storybook to document the changes
- [ ] I have provided documentation in the notes section of the story
- [ ] I have added any new public feature modules to public-api.ts
- [ ] I have [linked the new component](<(https://github.com/Legal-and-General/canopy/blob/master/docs/CONTRIBUTING.md#invision-dsm)>) to adobe DSM (if appropriate)

2021-02-03 18:56 UTC, thatguynamedandy approved these changes

2021-02-04 09:43 UTC, owensgit commented
Just a small one: the commit message for the typo has a typo 😉 

>docs: fix **type** with CODEOWNERS

"type" should be "typo"

Also wondering if we should add a scope for this commit message - perhaps `docs(contributing)`?

2021-02-04 09:44 UTC, owensgit requested changes
Just a small one: the commit message for the typo has a typo 😉

> docs: fix type with CODEOWNERS

"type" should be "typo"

Also wondering if we should add a scope for this commit message - perhaps docs(contributing)?

2021-02-04 09:58 UTC, elenagarrone commented
> Just a small one: the commit message for the typo has a typo 😉
> 
> > docs: fix type with CODEOWNERS
> 
> "type" should be "typo"
> 
> Also wondering if we should add a scope for this commit message - perhaps docs(contributing)?

🤣  that's funny :D 

I wasn't sure about the scope - I checked the previous docs commits from Andy and couldn't see anything so I left it blank :/ I'll add it.

2021-02-04 10:33 UTC, thatguynamedandy approved these changes

2021-02-04 11:18 UTC, owensgit approved these changes

2021-02-04 11:18 UTC, merged