fix(variants): add hover and active state style to variant buttons
Legal-and-General/canopy pull request #351
Opened 2021-05-07 12:35 UTC by AlexandruHoisan

# Description

Add styles for hover and active state, to variant buttons.

Note FYI: After a discussion with Michelle from the design team, we decided on this temporary solution until we design and build the component that combines the current Alert component, theDetail component, the Form Validation component and the Variant Directive that is being modified here. Inside variants we may only use the outline-primary button.

Implementation for pre-release branch( next ): [PR here](https://github.com/Legal-and-General/canopy/pull/350)

Storybook link: (once netlify has deployed link provide a link to the component)
Design link: [design link](https://legalandgeneral.invisionapp.com/console/share/SB10JVR247UQ/613975239/play)

# Checklist:

- [x] The commit messages follow the [convention for this project](./blob/master/docs/CONTRIBUTING.md#conventional-commits)
- [ ] I have provided an adequate amount of test coverage
- [ ] I have added the functionality to the [test app](./blob/master/docs/CONTRIBUTING.md#build-test-application)
- [ ] I have provided a story in storybook to document the changes
- [ ] I have provided documentation in the notes section of the story
- [ ] I have added any new public feature modules to public-api.ts

2021-05-07 13:07 UTC, AlexandruHoisan commented
> @AlexandruHoisan this seem to be breaking the links. I think you might need to apply the styles to the `.lg-btn` class.

@elenagarrone I do apply the styles to the `.lg-btn--outline-primary` class. This should not impact the links and from what I can see It does not impact the links, but I might be missing something. :)

2021-05-07 13:52 UTC, AlexandruHoisan commented on projects/canopy/src/lib/variant/variant.stories.ts
> +    notes: {
the notes were not showing for the variant because the `notes` have to be included in `parameters`. They were out of the parameters object. :)

2021-05-07 14:32 UTC, elenagarrone commented
> > @AlexandruHoisan this seem to be breaking the links. I think you might need to apply the styles to the `.lg-btn` class.
> 
> @elenagarrone I do apply the styles to the `.lg-btn--outline-primary` class. This should not impact the links and from what I can see It does not impact the links, but I might be missing something. :)

I'm not seeing the hover state on the link 🤔 

https://user-images.githubusercontent.com/8397116/117465173-52b50300-af49-11eb-8e7e-f18a34eb41dd.mov

2021-05-07 14:34 UTC, elenagarrone commented
> > > @AlexandruHoisan this seem to be breaking the links. I think you might need to apply the styles to the `.lg-btn` class.
> > 
> > 
> > @elenagarrone I do apply the styles to the `.lg-btn--outline-primary` class. This should not impact the links and from what I can see It does not impact the links, but I might be missing something. :)
> 
> I'm not seeing the hover state on the link 🤔 The below video is from the Variant directive story:
> 
>  Screen.Recording.2021-05-07.at.15.30.21.mov

I'm silly!!! Sorry @AlexandruHoisan I confused the link styles ;) I wasn't considering the fact that the new link style is only in the `next` branch!

2021-05-07 14:35 UTC, elenagarrone approved these changes

2021-05-07 14:43 UTC, elenagarrone requested changes
This will need the generic button border colour updated as per comments in other PR ;)

2021-05-10 09:04 UTC, AlexandruHoisan commented
> This will need the generic button border colour updated as per comments in other PR ;)

Done :)

2021-05-11 08:00 UTC, elenagarrone approved these changes

2021-05-11 09:05 UTC, merged